version: "3.9"

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"

  nginx-gen:
    container_name: nginx-gen
    image: jwilder/docker-gen
    restart: always
    command: -notify-sighup nginx -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - nginx:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /tmp/templates:/etc/docker-gen/templates

  dashy:
    container_name: dashy
    image: lissy93/dashy
    restart: always
    volumes:
      - ./roles/dashy/files/conf.yml:/app/public/conf.yml
    environment:
      VIRTUAL_HOST: "dashboard.degete.lan"
      VIRTUAL_PORT: "80"
    ports:
      - "8000:80"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    volumes:
      - ./roles/prometheus/files/prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      VIRTUAL_HOST: "prometheus.degete.lan"
      VIRTUAL_PORT: "9090"
    #ports:
      #- "9090:9090/tcp"

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    restart: always
    environment:
      VIRTUAL_HOST: "grafana.degete.lan"
      VIRTUAL_PORT: "3000"
    #ports:
      #- "3000:3000"

  adguard:
    container_name: adguard
    image: adguard/adguardhome
    restart: always
    volumes:
      - ./docker/adguard/work:/opt/adguardhome/work
      - ./docker/adguard/conf:/opt/adguardhome/conf
    environment:
      VIRTUAL_HOST: "adguard.degete.lan"
      VIRTUAL_PORT: "3000"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      #- "68:68/udp"
      #- "80:80/tcp"
      #- "443/tcp"
      #- "443/udp"
      - "784:784/udp"
      - "853:853/tcp"
      - "853:853/udp"
      #- "3000:3000/tcp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
      - "8853:8853/udp"

volumes:
  nginx: