- name: Install common packages
  become: yes
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - curl
      - git
      - jq
      - python3
      - python3-docker
      - python3-pip
      - python3-setuptools
      - python3-venv
      - screen
      - tmux
      - vim
      - wget
      - zsh