- name: Install common packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - acl
    - build-essential
    - ack
    - bat
    - curl
    - fish
    - fzf
    - git
    - htop
    - jq
    - neovim
    - python3
    - python3-pip
    - python3-setuptools
    - python3-venv
    - screen
    - tmux
    - vim
    - wget
    - zsh